apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:  # default limit
      cpu: 100m
      memory: "200Mi"
      ephemeral-storage: "100Mi"
    defaultRequest:  # default request
      cpu: 100m
      memory: "200Mi"
      ephemeral-storage: "100Mi"
    max:  # max value for each
      cpu: 200m
      memory: "400Mi"
      ephemeral-storage: "200Mi"
    min: # min value for each
      cpu: 50m
      memory: "100Mi"
      ephemeral-storage: "50Mi"
    type: Container
