apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    podname: pod-a
    env: prod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
  securityContext:
    runAsUser: 1000
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    podname: pod-b
    env: prod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME", "SYSLOG"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  labels:
    podname: pod-c
    env: prod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
  serviceAccountName: sa-a
  automountServiceAccountToken: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-d
  labels:
    podname: pod-d
    env: prod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    # volumeMounts:
    # - mountPath: /var/run/secrets/tokens
    #   name: vault-token
    volumeMounts:
    - name: vault-token
      mountPath: "/root/vault-token"
      readOnly: true
  # serviceAccountName: sa-a
  # automountServiceAccountToken: false
  volumes:
  - name: vault-token
    projected:
      sources:
      - secret:
          name: secret-a
  # - name: vault-token
  #   projected:
  #     sources:
  #     - serviceAccountToken:
  #         path: vault-token
  #         expirationSeconds: 7200
  #         audience: vault