apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-pc
value: 100
globalDefault: false
description: "High priority"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-pc
value: 10
globalDefault: false
description: "Low priority"