apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota-a
  namespace: default
spec:
  hard:
    # Limit
    limits.cpu: "1000m"
    limits.memory: "2000Mi"
    limits.ephemeral-storage: "2000Mi"
    persistentvolumeclaims: "2"
    # Request
    requests.cpu: "800m"
    requests.memory: "1800Mi"
    requests.storage: "3Gi"
    requests.ephemeral-storage: "1800Mi"
    # Obj quota
    count/deployments.apps: "2"
    pods: "6"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
  namespace: default
spec:
  hard:
    cpu: "300m"
    memory: "600Mi"
    pods: "3"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["high-pc"]
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-low
  namespace: default
spec:
  hard:
    cpu: "200m"
    memory: "400Mi"
    pods: "2"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["low-pc"]