apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: default
  labels:
    app: pod-b
    env: probe-test
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - name: http
      containerPort: 80
    livenessProbe:
      tcpSocket:
        port: http
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 80
        # httpHeaders:
        # - name: Custom-Header
        #   value: Awesome
      initialDelaySeconds: 15
      periodSeconds: 3
      successThreshold: 1
      failureThreshold: 5
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 20
      periodSeconds: 10
    volumeMounts:
    - mountPath: /root/lifecycle
      name: test-vol
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo $(hostname) : $(hostname  --ip-address) : Welcome !!! >> /root/index.html"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo $(hostname) : $(date) : This is pre-stop action >> /root/lifecycle/pre-stop.txt"]
  volumes:
  - name: test-vol
    hostPath:
      path: /root/podb/lifecycle
      type: DirectoryOrCreate



# spec:
#   containers:
#   ....
#     ports:
#     - name: 
#       containerPort:
#     livenessProbe:
#       tcpSocket:
#         port: http
#       initialDelaySeconds: 30
#       periodSeconds: 5
#       successThreshold: 1
#       failureThreshold: 10
#     readinessProbe:
#       httpGet:
#         path: /health
#         port: 80
#         httpHeaders:
#         - name: Custom-Header
#           value: Awesome
#         .... (same)
#     startupProbe:
#       exec:
#         command:
#         - cat
#         - /tmp/healthy
#       .... (same)
#     lifecycle:
#       postStart:
#         exec:
#           command: ["/bin/sh", "-c", "echo $(hostname) : $(hostname  --ip-address) : Welcome !!! >> /root/index.html"]
#       preStop:
#         exec:
#           command: ["/bin/sh", "-c", "echo $(hostname) : $(date) : This is pre-stop action >> /root/lifecycle/pre-stop.txt"]

