apiVersion: v1
kind: ConfigMap
metadata:
  name: config-a
  namespace: default
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "6"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
  user-name.json: |
    {
      name: luke
      age: 25
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-b
  namespace: default
data:
  SPECIAL_LEVEL: little
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-c
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
immutable: true
