apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: default
  labels:
    app: pod-a
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    # All key as env var
    envFrom:
    - secretRef:
        name: secret-a
    # Specific key as env var
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-a
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-a
          key: password
    volumeMounts:
    - name: secret-vol-1
      mountPath: "/etc/foo"
      readOnly: true
    - name: secret-vol-2
      mountPath: "/etc/bar"
      readOnly: true
  volumes:
  # All keys as mounted files
  - name: secret-vol-1
    secret:
      secretName: secret-b
      optional: true
  # Specific key as mounted files
  - name: secret-vol-2
    secret:
      secretName: secret-a
      items:
      - key: user-info.yaml
        path: user-info/.user-info.yaml


# spec:
#   ....
#     command: ["$(PODCMD)"]
#     args:
#     - "$(SLEEPMINUTE)"
#     ....
#     volumeMounts:
#     - name: 
#       mountPath: 
#       readOnly: true
#     envFrom:
#     - secretRef: / configMapRef:
#         name: 
#     env:
#     - name: 
#       valueFrom:
#         secretKeyRef: / configMapKeyRef:
#           name: 
#           key: 
#   volumes:
#   - name: 
#     secret:
#       secretName: / configMap:
#       optional: true (if secret exit, mount)
#   - name: 
#     secret:
#       secretName: /configMap:
#       items:
#       - key: 
#         path: .<file-name>


# -- External resources --
#  annotations:
#     kubernetes.io/service-account.name: "sa-name"
# type: Opaque , kubernetes.io/service-account-token ,
#       kubernetes.io/basic-auth , kubernetes.io/ssh-auth , kubernetes.io/tls
# data:
#   username: YWRtaW4K
#  tls.crt: |
#    MIIC2DCCAcCgAwIBAgIBATANBgkqh ...    
#  tls.key: |
#    MIIEpgIBAAKCAQEA7yn3bRHQ5FHMQ ... 
# stringData:
#   url_endpoint: "http://app.x.com"
#   user-info.yaml: |
#     user-age: "11"
#     user-location: "uae"
# extra: YmFyCg==
# immutable: true

 