apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: default
  labels:
    app: pod-a
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-a
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-a
          key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: default
  labels:
    app: pod-b
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-a
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  namespace: default
  labels:
    app: pod-c
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-a
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: secret-b
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-d
  namespace: default
  labels:
    app: pod-d
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args:
    - "3600"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: secret-a
      items:
      - key: user-info.yaml
        path: user-info/.user-info.yaml